#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Apr 28 13:16:13 2020

@author: olivia
"""

import sys
import os
import get_file_list
import getfiledata
import load_frames



dir='/data/ndr_calibration/NDR-Calibration_CDS/'
get_file_list(dir)
print(file_list)